### ISSUE TITLE
Editing money doesn't work

### ISSUE THREAD

**Issue by pmonks** [stolinator/w3se#10]
Not sure if this is a macOS specific problem or not, but editing money doesn't "stick", as seen in this screencap:

![money-bug](https://user-images.githubusercontent.com/54865/223290296-4ff10bed-4dcb-4f3d-85d5-522d8d93a6b1.gif)

I confirmed that editing other things (e.g. ammunition) does "stick", however.

**Environment:**
macOS 13.2.1 (on a 2019 Intel MBP)
Python 3.11.2
pip 23.0.1

**Comment by stolinator** [comment]
Thanks for pointing this out! I merged a fix for this [tested on macOS 12.5]
